version: "3.4"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    user: root
    restart: unless-stopped
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ALLOW_EMPTY_PASSWORD: achatdb
    volumes:
      - mysqldbb:/var/lib/mysql
    


  springapp:
    image: oumaima26/achat
    container_name: springapp
    restart: on-failure
    environment:
      -SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatdb?useUnicode=yes&&useJDBCCompliantTimezoneShift=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    volumes:
      - mysqldbb