version: "3"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=test
    ports:
      - "4000:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    image: 'wissembettaieb/achatrepo:wess'
    build:
      context: .

    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/test?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
volumes:
  db: