version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    user: root
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_ALLOW_EMPTY_PASSWORD: root
    volumes:
      - mysqldb:/var/lib/mysql:rw



  springapp:
    image: fakhriab/achatrepo
    container_name: achatproject
    restart: on-failure
    environment:
      -SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatdb?useUnicode=yes&&useJDBCCompliantTimezoneShift=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    volumes:
      - .m2:/root/.m2
    ports:
      - 8089:8089
    depends_on:
      - mysqldb





volumes:
  mysqldb:
